### ISSUE TITLE
ModuleNotFoundError: No module named 'ote_sdk' for classification example

### ISSUE THREAD

**Issue by antoniomtz** [openvinotoolkit/geti-sdk#277]
geti-sdk 1.5.0

Hello,
After I exported/deployed a classification model, I followed the README instructions on the zip file and after running the demo.py I get the following error:

> File "/app/env/lib/python3.8/site-packages/geti_sdk/deployment/deployed_model.py", line 301, in load_inference_model
>     spec.loader.exec_module(module)
>   File "<frozen importlib._bootstrap_external>", line 843, in exec_module
>   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
>   File "../deployment/Classification task/python/model_wrappers/__init__.py", line 15, in <module>
>     from .classification import Classification
>   File "/app/example_code/../deployment/Classification task/python/model_wrappers/classification.py", line 18, in <module>
>     from ote_sdk.utils.argument_checks import check_input_parameters_type
> **ModuleNotFoundError: No module named 'ote_sdk'**
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "demo.py", line 28, in <module>
>     deployment.load_inference_models(device="CPU")
>   File "/app/env/lib/python3.8/site-packages/geti_sdk/deployment/deployment.py", line 172, in load_inference_models
>     model.load_inference_model(device=device, project=self.project)
>   File "/app/env/lib/python3.8/site-packages/geti_sdk/deployment/deployed_model.py", line 303, in load_inference_model
>     raise ImportError(
> ImportError: Unable to load inference model for DeployedModel(name='EfficientNet-B0 OpenVINO FP32 with XAI head', fps_throughput='0', latency='0', precision=['FP32'], creation_date=datetime.datetime(2023, 3, 28, 16, 53, 57, 584000, tzinfo=datetime.timezone.utc), size=16252850, target_device='CPU', target_device_type=None, previous_revision_id='64231ba5afd18e20f53cab1c', previous_trained_revision_id='64231ba5afd18e20f53cab1c', score=None, performance={'score': 0.9355980184005662, 'local_score': None, 'global_score': None}, id='64231ba5afd18e20f53cab1d', label_schema_in_sync=None, model_status=<ModelStatus.SUCCESS: 'SUCCESS'>, optimization_methods=[], optimization_objectives={}, optimization_type=<OptimizationType.MO: 'MO'>, version=17, configurations=[], model_format='OpenVINO', has_xai_head=True). A custom model wrapperis required, but could not be found at path ../deployment/Classification task/python/model_wrappers.

There is no clear way to install ote_sdk using pip. 
Can I get some help solving this issue? Thanks.

**Comment by ljcornel** [comment]
Hi, and thanks for reporting this issue. The module `ote_sdk` was deprecated and replaced by `otx_api` as of Geti v1.5. If you create a deployment from Geti v1.5, it should no longer require `ote_sdk` but use `otx_api` instead. 

I've had a look at the deployment archive that you shared, it looks as if the requirements for the model somehow mismatch those of the deployment itself. Could it be that this model was trained in Geti v1.2 originally? If so, what may help is to trigger a re-training of the model in Geti v1.5, and then recreate the deployment. That should ensure that the requirements are in sync.

**Comment by ljcornel** [comment]
Closing because of inactivity
